-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 15:14:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema project_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_db` DEFAULT CHARACTER SET utf8 ;
USE `project_db` ;

-- -----------------------------------------------------
-- Table `project_db`.`Server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`Server` (
  `ser_id` INT NOT NULL AUTO_INCREMENT,
  `ser_creationDate` BIGINT(20) NULL,
  `ser_modificationDate` BIGINT(20) NULL,
  `ser_name` VARCHAR(255) NULL,
  `ser_ip` VARCHAR(255) NULL,
  PRIMARY KEY (`ser_id`),
  UNIQUE INDEX `o_id_UNIQUE` (`ser_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_db`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`Client` (
  `cli_id` INT NOT NULL AUTO_INCREMENT,
  `cli_creationDate` BIGINT(20) NULL,
  `cli_modificationDate` BIGINT(20) NULL,
  `cli_name` VARCHAR(255) NULL,
  `cli_address` VARCHAR(255) NULL,
  `cli_zipCode` DOUBLE NULL,
  `cli_city` VARCHAR(255) NULL,
  PRIMARY KEY (`cli_id`),
  UNIQUE INDEX `o_id_UNIQUE` (`cli_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_db`.`Partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`Partner` (
  `par_id` INT NOT NULL AUTO_INCREMENT,
  `par_creationDate` BIGINT(20) NULL,
  `par_modificationDate` BIGINT(20) NULL,
  `par_name` VARCHAR(255) NULL,
  PRIMARY KEY (`par_id`),
  UNIQUE INDEX `o_id_UNIQUE` (`par_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_db`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`Project` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_creationDate` BIGINT(20) NULL,
  `pro_modificationDate` BIGINT(20) NULL,
  `pro_name` VARCHAR(255) NULL,
  `pro_url` VARCHAR(255) NULL,
  `ser_id` INT NOT NULL,
  `cli_id` INT NOT NULL,
  `par_id` INT NOT NULL,
  PRIMARY KEY (`pro_id`),
  UNIQUE INDEX `o_id_UNIQUE` (`pro_id` ASC),
  INDEX `fk_Project_Server_idx` (`ser_id` ASC),
  INDEX `fk_Project_Client1_idx` (`cli_id` ASC),
  INDEX `fk_Project_Partner1_idx` (`par_id` ASC),
  CONSTRAINT `fk_Project_Server`
    FOREIGN KEY (`ser_id`)
    REFERENCES `project_db`.`Server` (`ser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Client1`
    FOREIGN KEY (`cli_id`)
    REFERENCES `project_db`.`Client` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Partner1`
    FOREIGN KEY (`par_id`)
    REFERENCES `project_db`.`Partner` (`par_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_db`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`Task` (
  `tas_id` INT NOT NULL AUTO_INCREMENT,
  `tas_creationDate` BIGINT(20) NULL,
  `tas_modificationDate` BIGINT(20) NULL,
  `tas_name` VARCHAR(255) NULL,
  `tas_state` TINYINT(1) NULL,
  PRIMARY KEY (`tas_id`),
  UNIQUE INDEX `o_id_UNIQUE` (`tas_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_db`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`Status` (
  `tas_id` INT NOT NULL,
  `pro_id` INT NOT NULL,
  `sta_name` VARCHAR(255) NULL,
  PRIMARY KEY (`tas_id`, `pro_id`),
  INDEX `fk_Task_has_Project_Project1_idx` (`pro_id` ASC),
  INDEX `fk_Task_has_Project_Task1_idx` (`tas_id` ASC),
  CONSTRAINT `fk_Task_has_Project_Task1`
    FOREIGN KEY (`tas_id`)
    REFERENCES `project_db`.`Task` (`tas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_has_Project_Project1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `project_db`.`Project` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
